[package]
name = "bgfx-imgui-glfw-rs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgfx-rs = "0.11"
glfw = "0.41"
raw-window-handle = "0.3"
stb = "0.3.2"
imgui = "0.8.0"
glam = "0.20.4"